# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Regexp-Match-List
version:      0.5
version_from: lib/Regexp/Match/List.pm
installdirs:  site
requires:
    Class::Base:                   
    Data::Dumper:                  
    Data::Sorting:                 

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
